import { ref, computed } from 'vue'
import { useQuasar } from 'quasar'
import { useResourceData } from '../../resources/useResourceData.js'
import { useResourceNav } from '../../resources/useResourceNav.js'
import { useWorkflowStore } from '../../../stores/workflow.js'
import { OUTLET_OPERATION_RESOURCES, VISIT_PROGRESS_ORDER, active, progressMeta, sortTime, text, todayISO, visitProgress } from './outletOperationsMeta.js'
import { OUTLET_ACTIONS, executeActionRequest, failureMessage, resourceCreateRequest, responseFailed } from './outletOperationsBatch.js'

export function useOutletVisits() {
  const $q = useQuasar(); const workflowStore = useWorkflowStore(); const nav = useResourceNav()
  const visits = useResourceData(ref('OutletVisits')); const outlets = useResourceData(ref('Outlets')); const rules = useResourceData(ref('OutletOperatingRules'))
  const loading = ref(false); const saving = ref(false); const searchTerm = ref(''); const form = ref({ Progress: 'PLANNED', ProgressPlannedComment: '', Status: 'Active', Date: todayISO() })
  const items = computed(() => visits.items.value.filter(active).filter(row => VISIT_PROGRESS_ORDER.includes(visitProgress(row))).filter(row => !searchTerm.value || JSON.stringify(row).toLowerCase().includes(searchTerm.value.toLowerCase())))
  const groups = computed(() => VISIT_PROGRESS_ORDER.map(key => ({ key, meta: progressMeta(key), items: items.value.filter(row => (VISIT_PROGRESS_ORDER.includes(visitProgress(row)) ? visitProgress(row) : 'OTHER') === key).sort((a, b) => sortTime(b) - sortTime(a)) })).filter(group => group.items.length))
  const outletOptions = computed(() => outlets.items.value.filter(active).map(row => ({ label: `${row.Code} · ${row.Name}`, value: row.Code })))
  async function reload(forceSync = false) { loading.value = true; try { await workflowStore.fetchResources(OUTLET_OPERATION_RESOURCES, { includeInactive: true, forceSync }) } finally { loading.value = false } }
  async function reloadIndex(forceSync = false) { loading.value = true; try { await workflowStore.fetchResources(['OutletVisits', 'Outlets'], { includeInactive: true, forceSync }) } finally { loading.value = false } }
  function addDaysISO(dateValue, days) { const base = text(dateValue) ? new Date(text(dateValue)) : new Date(); if (Number.isNaN(base.getTime())) base.setTime(Date.now()); base.setDate(base.getDate() + (Number(days) || 0)); return base.toISOString().slice(0, 10) }
  function visitFrequencyDays(outletCode) { const rule = rules.items.value.find(row => active(row) && text(row.OutletCode) === text(outletCode)); const days = Number(rule?.VisitFrequencyDays); return Number.isFinite(days) && days > 0 ? days : 14 }
  function plannedVisitRequest(visit, date, comment = '') { return resourceCreateRequest('OutletVisits', { OutletCode: text(visit?.OutletCode), Date: text(date), Progress: 'PLANNED', ProgressPlannedComment: text(comment), Status: 'Active' }) }
  async function createVisit() { if (!text(form.value.OutletCode) || !text(form.value.Date)) return $q.notify({ type: 'warning', message: 'Outlet and date are required.', position: 'top' }); saving.value = true; try { const result = await workflowStore.createResourceRecord('OutletVisits', { OutletCode: text(form.value.OutletCode), Date: text(form.value.Date), Progress: 'PLANNED', ProgressPlannedComment: text(form.value.ProgressPlannedComment), Status: 'Active' }); if (!result?.success) return $q.notify({ type: 'negative', message: result?.error || result?.message || 'Failed to create visit.', position: 'top' }); $q.notify({ type: 'positive', message: 'Visit planned.', position: 'top' }); nav.goTo('list') } finally { saving.value = false } }
  async function completeVisit(visit, fields = {}) { if (visitProgress(visit) !== 'PLANNED') { $q.notify({ type: 'warning', message: 'Only planned visits can be completed.', position: 'top' }); return false } saving.value = true; try { const nextDate = addDaysISO(visit.Date, visitFrequencyDays(visit.OutletCode)); const result = await workflowStore.runBatchRequests([executeActionRequest('OutletVisits', visit.Code, OUTLET_ACTIONS.completeVisit, { ProgressCompletedComment: text(fields.ProgressCompletedComment || fields.StatusCompletedComment || fields.StatusComment || fields.Comment) }), plannedVisitRequest(visit, nextDate, 'Auto planned after completed visit')]); if (responseFailed(result)) { $q.notify({ type: 'negative', message: failureMessage(result, 'Failed to complete visit.'), position: 'top' }); return false } $q.notify({ type: 'positive', message: 'Visit completed and next visit planned.', position: 'top' }); return true } finally { saving.value = false } }
  async function postponeVisit(visit, fields = {}) { if (!text(fields.ProgressPostponedComment || fields.StatusPostponedComment || fields.StatusComment || fields.Comment) || !text(fields.Date)) { $q.notify({ type: 'warning', message: 'Reason and new date are required.', position: 'top' }); return false } saving.value = true; try { const create = { OutletCode: visit.OutletCode, Date: text(fields.Date), Progress: 'PLANNED', ProgressPlannedComment: '', Status: 'Active' }; const result = await workflowStore.runBatchRequests([executeActionRequest('OutletVisits', visit.Code, OUTLET_ACTIONS.postponeVisit, { ProgressPostponedComment: text(fields.ProgressPostponedComment || fields.StatusPostponedComment || fields.StatusComment || fields.Comment) }), resourceCreateRequest('OutletVisits', create)]); if (responseFailed(result)) { $q.notify({ type: 'negative', message: failureMessage(result, 'Failed to postpone visit.'), position: 'top' }); return false } $q.notify({ type: 'positive', message: 'Visit postponed.', position: 'top' }); return true } finally { saving.value = false } }
  async function cancelVisit(visit, fields = {}) { const reason = text(fields.ProgressCancelledComment || fields.StatusCancelledComment || fields.StatusComment || fields.Comment || fields.reason || fields); if (!reason) { $q.notify({ type: 'warning', message: 'Cancellation reason is required.', position: 'top' }); return false } saving.value = true; try { const requests = [executeActionRequest('OutletVisits', visit.Code, OUTLET_ACTIONS.cancelVisit, { ProgressCancelledComment: reason })]; if (text(fields.Date || fields.nextDate)) requests.push(plannedVisitRequest(visit, text(fields.Date || fields.nextDate), 'Auto planned after cancelled visit')); const result = requests.length === 1 ? await workflowStore.executeResourceAction('OutletVisits', visit.Code, OUTLET_ACTIONS.cancelVisit, { ProgressCancelledComment: reason }) : await workflowStore.runBatchRequests(requests); if (requests.length === 1 ? !result?.success : responseFailed(result)) { $q.notify({ type: 'negative', message: requests.length === 1 ? (result?.error || result?.message || 'Failed to cancel visit.') : failureMessage(result, 'Failed to cancel visit.'), position: 'top' }); return false } $q.notify({ type: 'positive', message: text(fields.Date || fields.nextDate) ? 'Visit cancelled and next visit planned.' : 'Visit cancelled.', position: 'top' }); return true } finally { saving.value = false } }
  function getVisit(code) { return visits.items.value.find(row => row.Code === code) || null } function outletLabel(code) { const row = outlets.items.value.find(item => item.Code === code); return row ? `${row.Code} · ${row.Name}` : code } function navigateTo(code) { nav.goTo('view', { code }) } function navigateToAdd() { nav.goTo('add') } function cancel() { nav.goTo('list') }
  return { loading, saving, searchTerm, form, items, groups, outletOptions, reload, reloadIndex, createVisit, completeVisit, postponeVisit, cancelVisit, getVisit, outletLabel, progressMeta, navigateTo, navigateToAdd, cancel }
}
