import { ref, computed } from 'vue'
import { useQuasar } from 'quasar'
import { useResourceData } from '../../resources/useResourceData.js'
import { useResourceNav } from '../../resources/useResourceNav.js'
import { useWorkflowStore } from '../../../stores/workflow.js'
import { OUTLET_OPERATION_RESOURCES, active, progressMeta, sortTime, text, todayISO } from './outletOperationsMeta.js'
import { parseStorageAllocations, validateDelivery, remainingDeliveryQty, toNumber } from './outletStockLogic.js'
import { buildDeliveryCreateRequest, buildDeliveryPostRequests } from './outletRestockPayload.js'
import { failureMessage, responseFailed } from './outletOperationsBatch.js'

export function useOutletDeliveries() {
  const $q = useQuasar(); const workflowStore = useWorkflowStore(); const nav = useResourceNav(); const deliveries = useResourceData(ref('OutletDeliveries')); const restocks = useResourceData(ref('OutletRestocks')); const restockItems = useResourceData(ref('OutletRestockItems'))
  const loading = ref(false); const saving = ref(false); const searchTerm = ref(''); const selectedRestockCode = ref(''); const form = ref({ DeliveryDate: todayISO() }); const rows = ref([])
  const items = computed(() => deliveries.items.value.filter(active).filter(row => !searchTerm.value || JSON.stringify(row).toLowerCase().includes(searchTerm.value.toLowerCase())).sort((a, b) => sortTime(b) - sortTime(a)))
  const eligibleRestocks = computed(() => restocks.items.value.filter(active).filter(row => ['APPROVED', 'PARTIALLY_DELIVERED'].includes(text(row.Progress))))
  const restockOptions = computed(() => eligibleRestocks.value.map(row => ({ label: `${row.Code} · ${row.OutletCode} · ${progressMeta(row.Progress).label}`, value: row.Code })))
  const selectedRestock = computed(() => restocks.items.value.find(row => row.Code === selectedRestockCode.value) || null)
  async function reload(forceSync = false) { loading.value = true; try { await workflowStore.fetchResources(OUTLET_OPERATION_RESOURCES, { includeInactive: true, forceSync }) } finally { loading.value = false } }
  function selectRestock(code) { selectedRestockCode.value = code || ''; const source = restockItems.items.value.filter(row => row.OutletRestockCode === code).filter(active); rows.value = source.flatMap(row => { const remaining = remainingDeliveryQty(row, deliveries.items.value, code); const allocations = parseStorageAllocations(row.StorageAllocationJSON); return (allocations.length ? allocations : [{ storage_name: '_default', quantity: row.Quantity }]).map(allocation => ({ ...row, Code: `${row.Code}:${allocation.storage_name}`, OutletRestockItemCode: row.Code, StorageName: allocation.storage_name, AllocatedQty: toNumber(allocation.quantity), DeliveryQty: Math.min(remaining, toNumber(allocation.quantity)), RemainingQty: remaining })) }) }
  async function saveDelivery() { const selectedItems = restockItems.items.value.filter(row => row.OutletRestockCode === selectedRestockCode.value); const validation = validateDelivery(selectedRestock.value, selectedItems, rows.value, deliveries.items.value); if (!validation.valid) return $q.notify({ type: 'warning', message: validation.errors[0], position: 'top' }); saving.value = true; try { const createRequest = buildDeliveryCreateRequest(selectedRestock.value, form.value, rows.value); const createResult = await workflowStore.createResourceRecord('OutletDeliveries', createRequest.payload.record); if (!createResult?.success) return $q.notify({ type: 'negative', message: createResult?.error || createResult?.message || 'Failed to create delivery.', position: 'top' }); const code = createResult?.data?.result?.code || createResult?.data?.code || ''; if (!code) return $q.notify({ type: 'negative', message: 'Delivery was created but code was not returned for movement posting.', position: 'top' }); const postResult = await workflowStore.runBatchRequests(buildDeliveryPostRequests(code, selectedRestock.value, selectedItems.map(item => ({ ...item, DeliveredBefore: toNumber(item.Quantity) - remainingDeliveryQty(item, deliveries.items.value, selectedRestock.value?.Code) })), form.value, rows.value)); if (responseFailed(postResult)) return $q.notify({ type: 'negative', message: failureMessage(postResult, 'Failed to post delivery movements.'), position: 'top' }); $q.notify({ type: 'positive', message: 'Delivery saved.', position: 'top' }); nav.goTo('view', { code }) } finally { saving.value = false } }
  function updateRow(index, patch) { rows.value[index] = { ...rows.value[index], ...patch } } function parseDeliveryItems(delivery = {}) { try { return JSON.parse(delivery.DeliveredItemsJSON || '[]') } catch (_) { return [] } } function getDelivery(code) { return deliveries.items.value.find(row => row.Code === code) || null } function deliveredTotal(delivery) { return parseDeliveryItems(delivery).reduce((total, row) => total + toNumber(row.qty), 0) } function navigateTo(code) { nav.goTo('view', { code }) } function navigateToAdd() { nav.goTo('add') } function cancel() { nav.goTo('list') }
  return { loading, saving, searchTerm, selectedRestockCode, form, rows, items, eligibleRestocks, restockOptions, selectedRestock, reload, selectRestock, saveDelivery, updateRow, parseDeliveryItems, getDelivery, deliveredTotal, navigateTo, navigateToAdd, cancel }
}
