import { ref, computed } from 'vue'
import { useQuasar } from 'quasar'
import { useResourceData } from '../../resources/useResourceData.js'
import { useResourceNav } from '../../resources/useResourceNav.js'
import { useWorkflowStore } from '../../../stores/workflow.js'
import { OUTLET_OPERATION_RESOURCES, active, sortTime, text, todayISO } from './outletOperationsMeta.js'
import { validateConsumption, toNumber } from './outletStockLogic.js'
import { buildConsumptionCompositePayload, buildConsumptionMovementRequests } from './outletConsumptionPayload.js'
import { batchResultCode, compositeSaveRequest, failureMessage, responseFailed } from './outletOperationsBatch.js'

export function useOutletConsumption() {
  const $q = useQuasar(); const workflowStore = useWorkflowStore(); const nav = useResourceNav(); const consumption = useResourceData(ref('OutletConsumption')); const consumptionItems = useResourceData(ref('OutletConsumptionItems')); const storages = useResourceData(ref('OutletStorages')); const outlets = useResourceData(ref('Outlets'))
  const loading = ref(false); const saving = ref(false); const searchTerm = ref(''); const form = ref({ ConsumptionDate: todayISO(), Progress: 'CONFIRMED', Status: 'Active' }); const rows = ref([{ SKU: '', StorageName: '_default', ConsumedQty: 1, Status: 'Active' }])
  const items = computed(() => consumption.items.value.filter(active).filter(row => !searchTerm.value || JSON.stringify(row).toLowerCase().includes(searchTerm.value.toLowerCase())).sort((a, b) => sortTime(b) - sortTime(a)))
  const outletOptions = computed(() => outlets.items.value.filter(active).map(row => ({ label: `${row.Code} · ${row.Name}`, value: row.Code })))
  const stockOptions = computed(() => storages.items.value.filter(active).filter(row => !form.value.OutletCode || row.OutletCode === form.value.OutletCode).map(row => ({ label: `${row.SKU} · ${row.StorageName || '_default'} · ${row.Quantity}`, value: row.SKU, storage: row.StorageName })))
  async function reload(forceSync = false) { loading.value = true; try { await workflowStore.fetchResources(OUTLET_OPERATION_RESOURCES, { includeInactive: true, forceSync }) } finally { loading.value = false } }
  async function saveConsumption() { const validation = validateConsumption(form.value, rows.value, storages.items.value); if (!validation.valid) return $q.notify({ type: 'warning', message: validation.errors[0], position: 'top' }); saving.value = true; try { const saveRequest = compositeSaveRequest(buildConsumptionCompositePayload(form.value, rows.value)); const result = await workflowStore.runBatchRequests([saveRequest]); if (responseFailed(result)) return $q.notify({ type: 'negative', message: failureMessage(result, 'Failed to save consumption.'), position: 'top' }); const code = batchResultCode(result, 0); if (!code) return $q.notify({ type: 'negative', message: 'Consumption was saved but code was not returned for movement creation.', position: 'top' }); const movementRequest = buildConsumptionMovementRequests(code, form.value.OutletCode, rows.value, form.value); const movementResult = await workflowStore.uploadBulkRecords('OutletMovements', movementRequest.payload.records); if (!movementResult?.success) return $q.notify({ type: 'negative', message: movementResult?.error || movementResult?.message || 'Failed to post consumption movements.', position: 'top' }); $q.notify({ type: 'positive', message: 'Consumption saved.', position: 'top' }); nav.goTo('view', { code }) } finally { saving.value = false } }
  function addRow() { rows.value.push({ SKU: '', StorageName: '_default', ConsumedQty: 1, Status: 'Active' }) } function updateRow(index, patch) { rows.value[index] = { ...rows.value[index], ...patch } } function removeRow(index) { rows.value.splice(index, 1) } function getConsumption(code) { return consumption.items.value.find(row => row.Code === code) || null } function childItems(code) { return consumptionItems.items.value.filter(row => row.OutletConsumptionCode === code).filter(active) } function consumedTotal(code) { return childItems(code).reduce((sum, row) => sum + toNumber(row.ConsumedQty), 0) } function navigateTo(code) { nav.goTo('view', { code }) } function navigateToAdd() { nav.goTo('add') } function cancel() { nav.goTo('list') }
  return { loading, saving, searchTerm, form, rows, items, outletOptions, stockOptions, reload, saveConsumption, addRow, updateRow, removeRow, getConsumption, childItems, consumedTotal, navigateTo, navigateToAdd, cancel }
}
