import { ref, computed } from 'vue'
import { useQuasar } from 'quasar'
import { useAuthStore } from '../../../stores/auth.js'
import { useResourceData } from '../../resources/useResourceData.js'
import { useResourceNav } from '../../resources/useResourceNav.js'
import { useWorkflowStore } from '../../../stores/workflow.js'
import { OUTLET_OPERATION_RESOURCES, RESTOCK_PROGRESS_ORDER, active, progressMeta, sortTime, text, todayISO } from './outletOperationsMeta.js'
import { parseStorageAllocations, stringifyStorageAllocations, validateRestockApproval, validateRestockDraft, restockEditableProgress, sumBy, toNumber } from './outletStockLogic.js'
import { buildRestockCompositePayload } from './outletRestockPayload.js'
import { OUTLET_ACTIONS, batchResultCode, compositeSaveRequest, executeActionRequest, failureMessage, resourceBulkRequest, responseFailed } from './outletOperationsBatch.js'

export function resolveRestockViewMode(progress) { if (['DRAFT', 'REVISION_REQUIRED'].includes(text(progress))) return 'editable'; if (text(progress) === 'PENDING_APPROVAL') return 'review'; return 'readonly' }
export function useOutletRestocks() {
  const $q = useQuasar(); const workflowStore = useWorkflowStore(); const authStore = useAuthStore(); const nav = useResourceNav(); const restocks = useResourceData(ref('OutletRestocks')); const restockItems = useResourceData(ref('OutletRestockItems')); const outlets = useResourceData(ref('Outlets')); const skus = useResourceData(ref('SKUs')); const products = useResourceData(ref('Products')); const warehouseStorages = useResourceData(ref('WarehouseStorages'))
  const loading = ref(false); const saving = ref(false); const searchTerm = ref(''); const form = ref({ Date: todayISO(), RequestedUser: currentUserName(), Progress: 'DRAFT', Status: 'Active' }); const rows = ref([{ SKU: '', Quantity: 1, Status: 'Active' }])
  const items = computed(() => restocks.items.value.filter(active).filter(row => !searchTerm.value || JSON.stringify(row).toLowerCase().includes(searchTerm.value.toLowerCase())))
  const groups = computed(() => RESTOCK_PROGRESS_ORDER.map(key => ({ key, meta: progressMeta(key), items: items.value.filter(row => (RESTOCK_PROGRESS_ORDER.includes(row.Progress) ? row.Progress : 'OTHER') === key).sort((a, b) => sortTime(b) - sortTime(a)) })).filter(group => group.items.length))
  const outletOptions = computed(() => outlets.items.value.filter(active).map(row => ({ label: `${row.Code} · ${row.Name}`, value: row.Code })))
  const skuOptions = computed(() => skus.items.value.filter(active).map((sku) => { const product = products.items.value.find(row => row.Code === sku.ProductCode); const variants = [sku.Variant1, sku.Variant2, sku.Variant3, sku.Variant4, sku.Variant5].map(text).filter(Boolean).join(' / '); return { label: `${sku.Code} · ${product?.Name || sku.ProductCode || 'Product'}${variants ? ` · ${variants}` : ''}`, value: sku.Code } }))
  function storageOptionsForSku(sku) { return warehouseStorages.items.value.filter(active).filter(row => text(row.SKU) === text(sku) && toNumber(row.Quantity) > 0).map(row => ({ label: `${row.WarehouseCode || 'Warehouse'} · ${row.StorageName} · Available ${toNumber(row.Quantity)}`, value: row.StorageName, available: toNumber(row.Quantity), storage: row.StorageName, warehouseCode: row.WarehouseCode })) }
  function allocations(row = {}) { return parseStorageAllocations(row.StorageAllocationJSON) }
  function allocationTotal(row = {}) { return sumBy(allocations(row), 'quantity') }
  function allocationAvailability(row = {}) { return storageOptionsForSku(row.SKU) }
  function allocationAvailableTotal(row = {}) { return sumBy(allocationAvailability(row), 'available') }
  function updateAllocation(rowIndex, allocationIndex, patch) { const next = allocations(rows.value[rowIndex]); next[allocationIndex] = { ...(next[allocationIndex] || {}), ...patch }; updateRow(rowIndex, { StorageAllocationJSON: stringifyStorageAllocations(next) }) }
  function addAllocation(rowIndex) { const options = storageOptionsForSku(rows.value[rowIndex]?.SKU); const next = allocations(rows.value[rowIndex]); next.push({ storage_name: options[0]?.value || '', quantity: 0 }); updateRow(rowIndex, { StorageAllocationJSON: stringifyStorageAllocations(next) }) }
  function removeAllocation(rowIndex, allocationIndex) { const next = allocations(rows.value[rowIndex]); next.splice(allocationIndex, 1); updateRow(rowIndex, { StorageAllocationJSON: stringifyStorageAllocations(next) }) }
  function currentUserName() { const user = authStore.user || {}; return text(user.Name || user.name || user.UserName || user.Username || user.email || user.Email || user.UserID || user.Code) }
  function currentTimestampLabel(date = new Date()) { return date.toLocaleString('en-GB', { day: '2-digit', month: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false }) }
  function appendWorkflowComment(existingValue = '', comment = '', actorName = currentUserName(), date = new Date()) { const trimmedComment = text(comment); if (!trimmedComment) return text(existingValue); const nextEntry = `${actorName || 'Unknown User'} wrote at ${currentTimestampLabel(date)}:\n${trimmedComment}`; const base = text(existingValue); return base ? `${base}\n\n${nextEntry}` : nextEntry }
  function formatWorkflowCommentHtml(value = '') { return text(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;').replace(/\n/g, '<br>') }
  function submitCommentFields(restock = {}, comment = '') { return text(restock.Progress) === 'REVISION_REQUIRED' ? { ProgressRevisionRequiredComment: appendWorkflowComment(restock.ProgressRevisionRequiredComment, comment) } : { ProgressSubmittedComment: text(comment) ? appendWorkflowComment(restock.ProgressSubmittedComment, comment) : text(restock.ProgressSubmittedComment) } }
  function submissionSaveForm(restock = {}, comment = '') { return { ...form.value, Progress: 'PENDING_APPROVAL', ...submitCommentFields(restock, comment) } }
  function revisionCommentFields(restock = {}, comment = '') { return { ProgressRevisionRequiredComment: appendWorkflowComment(restock.ProgressRevisionRequiredComment, comment) } }
  function rejectedCommentFields(restock = {}, comment = '') { return { ProgressRejectedComment: text(comment) ? appendWorkflowComment(restock.ProgressRejectedComment, comment) : text(restock.ProgressRejectedComment) } }
  async function reload(forceSync = false) { loading.value = true; try { await workflowStore.fetchResources(OUTLET_OPERATION_RESOURCES, { includeInactive: true, forceSync }) } finally { loading.value = false } }
  async function reloadIndex(forceSync = false) { loading.value = true; try { await workflowStore.fetchResources(['OutletRestocks'], { includeInactive: true, forceSync }) } finally { loading.value = false } }
  async function reloadAdd(forceSync = false) { loading.value = true; try { await workflowStore.fetchResources(['Outlets', 'SKUs', 'Products'], { includeInactive: true, forceSync }) } finally { loading.value = false } }
  async function reloadView(forceSync = false) { loading.value = true; try { await workflowStore.fetchResources(['OutletRestocks', 'OutletRestockItems', 'WarehouseStorages', 'SKUs', 'Products'], { includeInactive: true, forceSync }) } finally { loading.value = false } }
  function loadRestock(code) { const record = restocks.items.value.find(row => row.Code === code); if (record) { form.value = { ...record, Date: text(record.Date) || todayISO(), RequestedUser: text(record.RequestedUser) || currentUserName() }; rows.value = restockItems.items.value.filter(row => row.OutletRestockCode === code).filter(active).map(row => ({ ...row })) } return record }
  function confirmWarnings(warnings = []) { if (!warnings.length) return Promise.resolve(true); return new Promise(resolve => { $q.dialog({ title: 'Confirm restock warnings', message: warnings.join('<br>'), html: true, cancel: true, persistent: true, ok: { label: 'Continue', color: 'primary' } }).onOk(() => resolve(true)).onCancel(() => resolve(false)).onDismiss(() => resolve(false)) }) }
  async function saveRestockDraft(submit = false, comment = '') { if (form.value.Code && !restockEditableProgress(form.value.Progress)) { $q.notify({ type: 'warning', message: `Restock ${form.value.Code} cannot be edited while progress is ${text(form.value.Progress) || 'blank'}.`, position: 'top' }); return false } if (submit && text(form.value.Progress) === 'REVISION_REQUIRED' && !text(comment)) { $q.notify({ type: 'warning', message: 'Resubmit comment is required.', position: 'top' }); return false } const validation = validateRestockDraft(form.value, rows.value); if (!validation.valid) { $q.notify({ type: 'warning', message: validation.errors[0], position: 'top' }); return false } if (!(await confirmWarnings(validation.warnings))) return false; saving.value = true; try { const payloadForm = submit ? submissionSaveForm(form.value, comment) : form.value; const saveResult = await workflowStore.runBatchRequests([compositeSaveRequest(buildRestockCompositePayload(payloadForm, rows.value))]); if (responseFailed(saveResult)) { $q.notify({ type: 'negative', message: failureMessage(saveResult, submit ? 'Failed to submit restock.' : 'Failed to save restock.'), position: 'top' }); return false } $q.notify({ type: 'positive', message: submit ? 'Restock submitted.' : 'Restock draft saved.', position: 'top' }); nav.goTo('list'); return true } finally { saving.value = false } }
  async function submitRestock(restock = form.value, comment = '') { if (!restockEditableProgress(restock.Progress)) { $q.notify({ type: 'warning', message: `Restock ${restock.Code} cannot be submitted while progress is ${text(restock.Progress) || 'blank'}.`, position: 'top' }); return false } if (text(restock.Progress) === 'REVISION_REQUIRED' && !text(comment)) { $q.notify({ type: 'warning', message: 'Resubmit comment is required.', position: 'top' }); return false } const validation = validateRestockDraft(restock, rows.value); if (!validation.valid) { $q.notify({ type: 'warning', message: validation.errors[0], position: 'top' }); return false } if (!(await confirmWarnings(validation.warnings))) return false; saving.value = true; try { const saveResult = await workflowStore.runBatchRequests([compositeSaveRequest(buildRestockCompositePayload(submissionSaveForm(restock, comment), rows.value))]); if (responseFailed(saveResult)) { $q.notify({ type: 'negative', message: failureMessage(saveResult, 'Failed to submit restock.'), position: 'top' }); return false } $q.notify({ type: 'positive', message: 'Restock submitted.', position: 'top' }); return true } finally { saving.value = false } }
  async function approveRestock(restock, approvedRows = rows.value, comment = '') { const validation = validateRestockApproval(restock, approvedRows); if (!validation.valid) { $q.notify({ type: 'warning', message: validation.errors[0], position: 'top' }); return false } saving.value = true; try { const itemUpdates = approvedRows.filter(active).map(row => ({ Code: row.Code, StorageAllocationJSON: text(row.StorageAllocationJSON) })).filter(row => row.Code); const result = await workflowStore.runBatchRequests([resourceBulkRequest('OutletRestockItems', itemUpdates), executeActionRequest('OutletRestocks', restock.Code, OUTLET_ACTIONS.approveRestock, { ApprovedUser: currentUserName(), ProgressApprovedComment: comment })]); if (responseFailed(result)) { $q.notify({ type: 'negative', message: failureMessage(result, 'Failed to approve restock.'), position: 'top' }); return false } $q.notify({ type: 'positive', message: 'Restock approved.', position: 'top' }); return true } finally { saving.value = false } }
  async function rejectRestock(restock, comment) { return transition(restock, OUTLET_ACTIONS.rejectRestock, rejectedCommentFields(restock, comment), 'Restock rejected.', comment) }
  async function sendBackRestock(restock, comment) { return transition(restock, OUTLET_ACTIONS.sendBackRestock, revisionCommentFields(restock, comment), 'Restock sent back.', comment) }
  async function transition(restock, action, fields, message, requiredComment = '') { if (!text(requiredComment)) { $q.notify({ type: 'warning', message: 'Comment is required.', position: 'top' }); return false } saving.value = true; try { const result = await workflowStore.executeResourceAction('OutletRestocks', restock.Code, action, fields); if (!result?.success) { $q.notify({ type: 'negative', message: result?.error || result?.message || 'Action failed.', position: 'top' }); return false } $q.notify({ type: 'positive', message, position: 'top' }); return true } finally { saving.value = false } }
  function addRow() { rows.value.push({ SKU: '', Quantity: 1, Status: 'Active' }) } function updateRow(index, patch) { rows.value[index] = { ...rows.value[index], ...patch } } function removeRow(index) { rows.value.splice(index, 1) } function getRestock(code) { return restocks.items.value.find(row => row.Code === code) || null } function childItems(code) { return restockItems.items.value.filter(row => row.OutletRestockCode === code).filter(active) } function navigateTo(code) { nav.goTo('view', { code }) } function navigateToAdd() { nav.goTo('add') } function cancel() { nav.goTo('list') }
  return { loading, saving, searchTerm, form, rows, items, groups, outletOptions, skuOptions, reload, reloadIndex, reloadAdd, reloadView, loadRestock, saveRestockDraft, submitRestock, approveRestock, rejectRestock, sendBackRestock, resolveRestockViewMode, addRow, updateRow, removeRow, getRestock, childItems, progressMeta, storageOptionsForSku, allocations, allocationTotal, allocationAvailability, allocationAvailableTotal, updateAllocation, addAllocation, removeAllocation, appendWorkflowComment, formatWorkflowCommentHtml, navigateTo, navigateToAdd, cancel }
}
